# Generated by Django 3.0.3 on 2020-04-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='slug',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
    ]
